# Generated by Django 5.2.4 on 2025-08-18 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_atributes_write'),
        ('teleg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('tocken', models.CharField(blank=True, max_length=200, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.atributes')),
            ],
        ),
    ]
