# Generated by Django 5.2.4 on 2025-08-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributes',
            name='write',
            field=models.BooleanField(default=False),
        ),
    ]
