# Generated by Django 5.2.4 on 2025-08-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_atributes_write'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributes',
            name='alarm_atr',
            field=models.BooleanField(default=False),
        ),
    ]
