# Generated by Django 5.2.7 on 2025-10-21 12:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_fix_subscription_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='obj',
            name='manager_notes',
            field=models.TextField(blank=True, help_text='Внутренние заметки о клиенте и объекте', verbose_name='Заметки менеджера'),
        ),
        migrations.AlterField(
            model_name='addonmodule',
            name='ai_requests_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Лимит AI запросов/месяц'),
        ),
        migrations.AlterField(
            model_name='addonmodule',
            name='automation_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='Уровень автоматизации'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='addons_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Цена модулей ($)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Базовая цена ($)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='data.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Оплачено до'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Итоговая цена ($)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='has_api_access',
            field=models.BooleanField(default=False, verbose_name='API доступ'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='has_custom_reports',
            field=models.BooleanField(default=False, verbose_name='Кастомные отчёты'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='has_white_label',
            field=models.BooleanField(default=False, verbose_name='White-label брендинг'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_objects',
            field=models.IntegerField(default=3, verbose_name='Максимум объектов'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_systems',
            field=models.IntegerField(default=10, verbose_name='Максимум систем'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.IntegerField(default=5, verbose_name='Максимум пользователей'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название тарифа'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в месяц ($)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_yearly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена в год ($)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Company Admin'), ('manager', 'Manager'), ('client', 'Client')], default='client', help_text='Phase 4.1: Updated role system', max_length=20, verbose_name='Роль'),
        ),
    ]
