# Generated by Django 5.2.7 on 2025-10-22 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_add_manager_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время срабатывания')),
                ('value', models.FloatField(verbose_name='Значение при срабатывании')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('acknowledged', 'Подтверждена'), ('resolved', 'Решена'), ('snoozed', 'Отложена'), ('ignored', 'Игнорирована')], default='active', max_length=20, verbose_name='Статус')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время решения')),
                ('snooze_until', models.DateTimeField(blank=True, null=True, verbose_name='Отложена до')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Подтверждена')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Решена')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='data.alertrule', verbose_name='Правило')),
                ('snoozed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snoozed_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Отложена')),
            ],
            options={
                'verbose_name': 'Событие тревоги',
                'verbose_name_plural': 'События тревог',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='data.alertevent', verbose_name='Тревога')),
            ],
            options={
                'verbose_name': 'Комментарий к тревоге',
                'verbose_name_plural': 'Комментарии к тревогам',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['status', '-triggered_at'], name='data_alerte_status_e0ebc2_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['rule', 'status'], name='data_alerte_rule_id_86c178_idx'),
        ),
    ]
