# Generated by Django 5.2.7 on 2025-10-22 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alertevent_alertcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('actuator_type', models.CharField(choices=[('valve', '🚰 Клапан'), ('relay', '⚡ Реле'), ('motor', '⚙️ Мотор'), ('switch', '💡 Выключатель'), ('dimmer', '🔆 Диммер'), ('pump', '💧 Насос'), ('fan', '🌀 Вентилятор'), ('heater', '🔥 Нагреватель'), ('cooler', '❄️ Охладитель')], max_length=20, verbose_name='Тип устройства')),
                ('modbus_carel', models.BooleanField(default=True, verbose_name='Modbus/CAREL')),
                ('register', models.IntegerField(blank=True, null=True, verbose_name='Регистр Modbus')),
                ('carel_reg', models.CharField(blank=True, max_length=50, verbose_name='Переменная CAREL')),
                ('register_type', models.CharField(choices=[('HD', 'Holding Register'), ('CL', 'Coil')], default='HD', max_length=2, verbose_name='Тип регистра')),
                ('min_value', models.FloatField(default=0, verbose_name='Минимальное значение')),
                ('max_value', models.FloatField(default=100, verbose_name='Максимальное значение')),
                ('default_value', models.FloatField(default=0, verbose_name='Значение по умолчанию')),
                ('current_value', models.FloatField(blank=True, null=True, verbose_name='Текущее значение')),
                ('last_command_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя команда')),
                ('uom', models.CharField(blank=True, default='%', max_length=20, verbose_name='Ед. изм.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_online', models.BooleanField(default=False, verbose_name='В сети')),
                ('sys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuators', to='data.system', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'Исполнительное устройство',
                'verbose_name_plural': 'Исполнительные устройства',
                'ordering': ['sys', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActuatorCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_value', models.FloatField(verbose_name='Заданное значение')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время выполнения')),
                ('status', models.CharField(choices=[('pending', '⏳ Ожидает'), ('success', '✅ Выполнена'), ('failed', '❌ Ошибка'), ('timeout', '⏱️ Таймаут')], default='pending', max_length=20, verbose_name='Статус')),
                ('response_time_ms', models.IntegerField(blank=True, null=True, verbose_name='Время отклика (мс)')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP источника')),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='data.actuator', verbose_name='Устройство')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuator_commands', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Команда управления',
                'verbose_name_plural': 'Команды управления',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='actuator',
            index=models.Index(fields=['sys', 'is_active'], name='data_actuat_sys_id_23ede8_idx'),
        ),
        migrations.AddIndex(
            model_name='actuator',
            index=models.Index(fields=['actuator_type'], name='data_actuat_actuato_d49365_idx'),
        ),
        migrations.AddIndex(
            model_name='actuatorcommand',
            index=models.Index(fields=['actuator', '-executed_at'], name='data_actuat_actuato_66872d_idx'),
        ),
        migrations.AddIndex(
            model_name='actuatorcommand',
            index=models.Index(fields=['user', '-executed_at'], name='data_actuat_user_id_0db39f_idx'),
        ),
        migrations.AddIndex(
            model_name='actuatorcommand',
            index=models.Index(fields=['status', '-executed_at'], name='data_actuat_status_8598a7_idx'),
        ),
    ]
