# Generated by Django 5.2.7 on 2025-10-23 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_add_sensordata_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sensordata',
            new_name='data_sensor_timesta_4090bf_idx',
            old_name='data_sensor_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='sensordata',
            new_name='data_sensor_sensor__e95ba5_idx',
            old_name='data_sensor_sensor_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='sensordata',
            new_name='data_sensor_connect_5dd176_idx',
            old_name='data_sensor_connect_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='sensordata',
            new_name='data_sensor_registe_b26301_idx',
            old_name='data_sensor_registe_timesta_idx',
        ),
    ]
